{{- if eq .Values.filestore.backend "filesystem" -}}
{{- if and .Values.filestore.filesystem.persistence.enabled (not .Values.filestore.filesystem.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "sentry.fullname" . }}-data
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.filestore.filesystem.persistence.annotations }}
    annotations: {{- toYaml .Values.filestore.filesystem.persistence.annotations | nindent 6 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.filestore.filesystem.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.filestore.filesystem.persistence.size | quote }}
  {{- if .Values.filestore.filesystem.persistence.selector }}
  selector: {{- toYaml .Values.filestore.filesystem.persistence.selector | nindent 4 }}
  {{- end }}
{{- if .Values.filestore.filesystem.persistence.storageClass }}
{{- if (eq "-" .Values.filestore.filesystem.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.filestore.filesystem.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
